import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.kover)
}

android {
    namespace = "com.clearcmos.kata"
    compileSdk = 36
    // Pinned so the read-only nix SDK is never asked to download a different revision.
    buildToolsVersion = "35.0.0"

    defaultConfig {
        applicationId = "com.clearcmos.kata"
        // 34 so the Android 14 foreground-service-type rules and the exact-alarm
        // permission split are both unconditional; no version guards in engine code.
        minSdk = 34
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        // android.jar stubs return defaults instead of throwing, so the storage classes' own
        // logging on a failure path does not blow up the JVM test that is exercising it.
        unitTests.isReturnDefaultValues = true
    }

    lint {
        warningsAsErrors = true
        abortOnError = true
        // Version-drift checks would fail on every upstream release; dependency and SDK
        // bumps are deliberate, reviewed changes here.
        disable += setOf("GradleDependency", "AndroidGradlePluginVersion", "NewerVersionAvailable", "OldTargetApi")
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

ktlint {
    android.set(true)
    outputToConsole.set(true)
}

kover {
    reports {
        filters {
            excludes {
                // Android-bound classes verified on the device, not in JVM tests. Each is listed
                // with its reason in CLAUDE.md under "Test exemptions".
                classes(
                    // Generated by view binding; not this project's code.
                    "com.clearcmos.kata.databinding.*",
                    "com.clearcmos.kata.ui.*",
                    "com.clearcmos.kata.engine.KataService*",
                    "com.clearcmos.kata.engine.Kata",
                    "com.clearcmos.kata.engine.Notifications",
                    "com.clearcmos.kata.engine.DeviceState",
                    "com.clearcmos.kata.actions.ActionRunner*",
                    "com.clearcmos.kata.actions.SshClient*",
                    "com.clearcmos.kata.api.ApiToken*",
                    "com.clearcmos.kata.api.Capabilities",
                    "com.clearcmos.kata.triggers.*"
                )
            }
        }
        variant("debug") {
            verify {
                rule("line coverage of the JVM-testable modules") {
                    // Ratchet: measured 92.9% on 2026-08-31. Raise this when coverage
                    // rises, never lower it to make a change fit.
                    minBound(90)
                }
            }
        }
    }
}

// Every resolvable configuration is locked; gradle.lockfile is the ecosystem lockfile.
// Refresh deliberately with: gradle dependencies :app:dependencies --write-locks
dependencyLocking {
    lockAllConfigurations()
}

dependencies {
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.recyclerview)
    implementation(libs.material)
    implementation(libs.jsch)
    testImplementation(libs.junit)
    // Shadows the android.jar org.json stubs in unit tests; see the note in libs.versions.toml.
    testImplementation(libs.json)
}
